# Generated by Django 5.2.8 on 2025-12-04 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='game_state',
            new_name='board_p1',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='score',
            new_name='score_p2',
        ),
        migrations.AddField(
            model_name='room',
            name='board_p2',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='room',
            name='is_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='player1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms_as_p1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='player2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms_as_p2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='score_p1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='winner',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
